-- create system module tables --
--add by Angie --

-- dictionary type table --
DROP TABLE SYS_DICT_TYPE;
CREATE TABLE SYS_DICT_TYPE
(
 CODEID	VARCHAR(20) NOT NULL COMMENT '编号',
 NAME	VARCHAR(20) NOT NULL COMMENT '名称',
ISEDITABLE	BOOL NOT NULL COMMENT '是否可编辑',
DETAIL	VARCHAR(64) NOT NULL COMMENT '说明',
PRIMARY KEY (CODEID)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

-- dictionary info table --
DROP TABLE SYS_DICT_INFO;
CREATE TABLE SYS_DICT_INFO
(
 DICTID	VARCHAR(20) NOT NULL COMMENT '编号',
 NAME	VARCHAR(20) NOT NULL COMMENT '名称',
 VALUE	VARCHAR(20) NOT NULL COMMENT '取值',
 CODEID	VARCHAR(20) NOT NULL COMMENT '数据字典类型',
 ORDERNO SMALLINT NOT NULL COMMENT '顺序',
 DETAIL	VARCHAR(64) NOT NULL COMMENT '说明',
 PRIMARY KEY (DICTID),
 FOREIGN KEY(CODEID) REFERENCES SYS_DICT_TYPE(CODEID)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

-- system parameter table --
DROP TABLE SYS_PARAM;
CREATE TABLE SYS_PARAM
(
 ID	SMALLINT NOT NULL COMMENT '编号',
 NAME	VARCHAR(20) NOT NULL COMMENT '名称',
 VALUE	VARCHAR(30) NOT NULL COMMENT '取值',
 DETAIL	VARCHAR(64) NOT NULL COMMENT '说明',
 CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
 UPDATE_TIME DATETIME COMMENT '修改时间',
 PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

-- menu info table --
DROP TABLE SYS_MENUINFO;
CREATE TABLE SYS_MENUINFO
(
 MENUID SMALLINT NOT NULL COMMENT '菜单编号',
 MENUNAME VARCHAR(20) NOT NULL COMMENT '菜单名称',
 URL VARCHAR(128) NOT NULL COMMENT '链接URL',
 PARENTID VARCHAR(64) NOT NULL COMMENT '父级菜单编号',
 ORDERNO SMALLINT NOT NULL COMMENT '顺序',
 CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
 UPDATE_TIME DATETIME COMMENT '修改时间',
 PRIMARY KEY (MENUID)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
